[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.13"
optimizer = true
optimizer_runs = 200

# RPC endpoints
[rpc_endpoints]
SEPOLIA_RPC_URL = "https://sepolia.infura.io/v3/de993052a152468cae6e7f290f914460"
localhost = "http://localhost:8545"

# HAPUS bagian private_key dari sini - tidak aman!
# private_key akan diambil dari environment variable

# Etherscan untuk verifikasi
[etherscan]
sepolia = { key = "${ND8BA8EMN7KK26X7B8ZAC9G5ECH1CCC2NW}" }